version: "3"

services:
  database:
    build:
      context: ./docker/database
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_SCHEMA}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASS}
    container_name: ${APP_NAME:?err}-mariadb
    ports:
      - "3306:3306"
    volumes:
      - './docker/database/data:/var/lib/mysql'
      - './docker/database/init:/docker-entrypoint-initdb.d'
    networks:
      - rnr

  fpm:
    build:
      context: ./docker/fpm
    container_name: fpm
    volumes:
      - './:/var/www'
      - './logs:/var/log'
    ports:
      - "9000:9000"
    networks:
      - rnr
    depends_on:
      - database

  nginx:
    build:
      context: ./docker/nginx
    container_name: ${APP_NAME:?err}-nginx
    ports:
      - "3333:80"
    volumes:
      - './logs:/var/log/nginx'
      - './:/var/www'
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './docker/nginx/sites-enabled:/etc/nginx/sites-enabled'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    networks:
      - rnr
    links:
      - fpm
    depends_on:
      - fpm



networks:
  rnr:
    driver: bridge
